// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC643pV6mcm8G08QAXAcEA05Rv48qwcgVM',
    appId: '1:237171077217:web:07332b272c77c93f3f7a20',
    messagingSenderId: '237171077217',
    projectId: 'smart-lighting-01',
    authDomain: 'smart-lighting-01.firebaseapp.com',
    storageBucket: 'smart-lighting-01.firebasestorage.app',
    measurementId: 'G-3RRV8SQ0WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt-9u6FwzKk6SHOQK_ZGnCKVM_xmRahvI',
    appId: '1:237171077217:android:73d43790da9cfcf93f7a20',
    messagingSenderId: '237171077217',
    projectId: 'smart-lighting-01',
    storageBucket: 'smart-lighting-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6b0tfYgVSo-DHRLtu1wTtlnrB76sbYGc',
    appId: '1:237171077217:ios:7ce834583f911b533f7a20',
    messagingSenderId: '237171077217',
    projectId: 'smart-lighting-01',
    storageBucket: 'smart-lighting-01.firebasestorage.app',
    iosBundleId: 'com.example.smartLighting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6b0tfYgVSo-DHRLtu1wTtlnrB76sbYGc',
    appId: '1:237171077217:ios:7ce834583f911b533f7a20',
    messagingSenderId: '237171077217',
    projectId: 'smart-lighting-01',
    storageBucket: 'smart-lighting-01.firebasestorage.app',
    iosBundleId: 'com.example.smartLighting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC643pV6mcm8G08QAXAcEA05Rv48qwcgVM',
    appId: '1:237171077217:web:bd744adc5c1a6c0d3f7a20',
    messagingSenderId: '237171077217',
    projectId: 'smart-lighting-01',
    authDomain: 'smart-lighting-01.firebaseapp.com',
    storageBucket: 'smart-lighting-01.firebasestorage.app',
    measurementId: 'G-B0RPWG2XQR',
  );

}